### ISSUE TITLE
Skeleton setup for Gateway Architecture

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/Brogrammers#1]
Define the architecture and skeleton for communication via REST API's

**Comment by Arjunbhavsar** [comment]
Spring boot Application Has been created to publish Rest API. 

Web module will share all the data request through this microservice.

**Comment by Arjunbhavsar** [comment]
I am able to register new User with an input given below 

 {
        "id": null,
        "name": "Arjun",
        "mobileNumber": null,
        "address": null,
        "emailID": null,
        "password": "1234@1234"
    }

Which is generating output json as - 

{
    "id": "5e3c86dd94e898265e2a0254",
    "name": "Arjun",
    "mobileNumber": null,
    "address": null,
    "emailID": null,
    "password": "1234@1234",
    "status": "Registered"
}

**Comment by Arjunbhavsar** [comment]
Commit Link - 

https://github.com/airavata-courses/Brogrammers/commit/259890ce408df179572c476e75c249eaaf6613df
