### ISSUE TITLE
Bug in Initial testing of landing page

### ISSUE THREAD

**Issue by rgrishigajra** [airavata-courses/Brogrammers#16]
The register option for new users allows multiple sign up attempts from the same EMail id and username. The email should be unique and an error message saying something like "email already exists" should appear I suggest.

**Comment by knikharg** [comment]
Issue resolved with https://github.com/airavata-courses/Brogrammers/commit/abaca115a2203ed95a26363283c41e0ac8db3e6e 
Validations added to check if user already exists and if user not found.

**Comment by rgrishigajra** [comment]
Yeah its working as inteded now. Closing issue.
