### ISSUE TITLE
Password should be secured while implementing login

### ISSUE THREAD

**Issue by bivasmaiti26** [airavata-courses/Brogrammers#23]

**Comment by ishita-kumar** [comment]
Done, through front end 
d11040aff22c6471205270fa997b24777694c848

**Comment by Arjunbhavsar** [comment]
Completed the changes In the backend facing merge Issues with Branch - Feature_Gateway_V1

**Comment by Arjunbhavsar** [comment]
commit 14a9d2733ebafc71eac66cb37d0a28f98386a70d

Done through backend
