### ISSUE TITLE
Test Failures while running Gateway and User management services

### ISSUE THREAD

**Issue by arpit2010** [airavata-courses/Brogrammers#24]
https://files.slack.com/files-pri/T0VST4W8P-FUC4FFV5J/image.png (let me know if you are unable to open the image)

while i am running your gateway and user management services, i am getting this test failure as it is unable to detect your spring boot annotation.

**Comment by ishita-kumar** [comment]
Hi ! 
Please Try the following : 
Go to pom -> right click -> run -> build maven >
Enter  > clean install in goal 
And then apply


This should work

**Comment by Arjunbhavsar** [comment]
commit 89289b860dab3d733c1fc33ad75c89ecc122b077

Issue Resolved With following commit
