### ISSUE TITLE
Duplicate bucket name error in AWS

### ISSUE THREAD

**Issue by arpit2010** [airavata-courses/Brogrammers#25]
https://files.slack.com/files-pri/T0VST4W8P-FUEDS6M0F/issue_s3.jpg (let me know if you are not able to access the image)

While creating an S3 bucket on AWS, it has been mentioned to name bucket as "ads-plots" but I am getting duplicate bucket error as shown in the screenshot.

**Comment by knikharg** [comment]
Hi
I have deleted my existing bucket, you can go ahead and create your own with the name "ads-plots"

**Comment by knikharg** [comment]
https://github.com/airavata-courses/Brogrammers/commit/049931b68cdb052fbd0df5c886d059ff4d15981e

**Comment by knikharg** [comment]
removed dependency from AWS

**Comment by Arjunbhavsar** [comment]
commit d3b31cda1e3a350dc2f6e7a9d59ecb2216bfffd4
