### ISSUE TITLE
Containerize services using docker

### ISSUE THREAD

**Issue by knikharg** [airavata-courses/Brogrammers#28]
Started by creating DockerFile for each of the services

**Comment by Arjunbhavsar** [comment]
https://github.com/airavata-courses/Brogrammers/commit/308af263edd833ef15ea4afb2482d956fc770357

**Comment by knikharg** [comment]
https://github.com/airavata-courses/Brogrammers/commit/693219dd7311f254f9292b41a18f8ef1efa4f13d

**Comment by Arjunbhavsar** [comment]
commit 31d6c06441f5b113ad4528ab3f7ad3a2d3c2d11e
