### ISSUE TITLE
Containerizing rabbitmq and establishing connection with microservices 

### ISSUE THREAD

**Issue by knikharg** [airavata-courses/Brogrammers#29]
AMPQ connection error while running data-retrieval container. Tried using links to establish connections.

**Comment by knikharg** [comment]
communication achieved by replacing host to image name.

**Comment by Arjunbhavsar** [comment]
We need installed rabbit MQ over the network. This can be achieved by having a dependency on the Rabbitmq to each microservice which is trying to connect to the rabbitmq network.

I tried to achieve this with following commit id -- 308af263edd833ef15ea4afb2482d956fc770357

**Comment by Arjunbhavsar** [comment]
Referred the following document to install the Rabbit MQ on the Kubernetes Cluster 

https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/


Issue resolved on the Kubernetes cluster
