### ISSUE TITLE
Database Creation and Connection 

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/Brogrammers#3]
Research on best suited Database, and practices..

**Comment by knikharg** [comment]
Issue resolved with https://github.com/airavata-courses/Brogrammers/commit/ca8225a5cd8b68a3cdfe70e9b31a757163eb403b

**Comment by knikharg** [comment]
Database chosen : mongodb
Easy to retrieve and expand. Better suited for the kind of data we are dealing with as here entities do not have a strict relationship
