### ISSUE TITLE
Jenkins Continuous Integration 

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/Brogrammers#30]
Pipelines for each branch must be created. Use 5 minute window and add webhooks for each job commit.

**Comment by knikharg** [comment]
Added kube config to Jenkinsfile https://github.com/airavata-courses/Brogrammers/commit/a3cb26190a9825f51a8b4bb799a9530de3b2643f

**Comment by Arjunbhavsar** [comment]
9b2ee28

57b5e2d
