### ISSUE TITLE
kubernetes instances

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/Brogrammers#32]
Create master and 2 minions with Kubernetes and add pods to it

**Comment by Arjunbhavsar** [comment]
900ba9718e9316a2950a447a2e516fadc3c4f074

**Comment by Arjunbhavsar** [comment]
aac3cd5664132284f0e39c8e9ffac4a8797718bf


Committed the Yaml files for all the Kubernetes deployment
