### ISSUE TITLE
OnClick Plot.js Not found

### ISSUE THREAD

**Issue by ghost** [airavata-courses/Brogrammers#34]
![image](https://user-images.githubusercontent.com/39978963/77213451-4077cb80-6ae1-11ea-9864-05080785e0f5.png)

I get the following error as soon as I  click on the button after giving the details for reflexivity graph

**Comment by Arjunbhavsar** [comment]
Resolved -- Please Test Again

**Comment by ghost** [comment]
I am unable to login now. Raised a new issue #35
