### ISSUE TITLE
Testing and Evaluation of API

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/Brogrammers#5]
API request response via POSTMAN

**Comment by Arjunbhavsar** [comment]
Tested the API's For User Handling Module.

->http://localhost:8080/rest/getusers
->http://localhost:8080/rest/login
->http://localhost:8080/rest/user/register
->http://localhost:8080/rest/user/signOut

**Comment by ishita-kumar** [comment]
Tested APIS for session Management Via Postman 
http://localhost:4001/sessionMannagement
