### ISSUE TITLE
Integrating Communication between Gateway and web module

### ISSUE THREAD

**Issue by ishita-kumar** [airavata-courses/Brogrammers#7]
Spring Boot and Design

**Comment by Arjunbhavsar** [comment]
Unable to Consume a Published API from React Front end through Axios request.

Getting following Error - 

access to XMLHttpRequest at 'http://localhost:8080/rest/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested reso

**Comment by ishita-kumar** [comment]
Issue resolved, cross origins decoration added. 
Commit ID 5a6748a0486b42643aee62e4844562bdab0d0053
