### ISSUE TITLE
Data retrieval Module

### ISSUE THREAD

**Issue by knikharg** [airavata-courses/Brogrammers#9]
Access data according to user inputs and process further to model execution.

**Comment by knikharg** [comment]
Database chosen : mongodb 
Easy to retrieve and expand. Better suited for the kind of data we are dealing with as here entities do not have a strict relationship

**Comment by Arjunbhavsar** [comment]
Communication Established With Gateway and I am able to fetch the JSON response at Data Retrieval Microservice.
As below- 

![Capture](https://user-images.githubusercontent.com/28916367/74094531-d36c2180-4ab0-11ea-83de-b3650c7575ce.PNG)
